#!/usr/bin/env python3
"""Create a simple 2D gas heatmap from simulated gas samples.

This is intentionally not a real ROS2 node yet. It reads a CSV generated by
gas_sensor_node.py and produces a PNG heatmap for the demo report.

TODO: Replace CSV polling with ROS2 topic/subscription based map updates.
"""

from __future__ import annotations

import argparse
import contextlib
import csv
import io
import json
import math
import re
import shutil
from pathlib import Path


REQUIRED_COLUMNS = {
    "x",
    "y",
    "ppm",
}


def parse_args() -> argparse.Namespace:
    project_dir = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description="Generate a 2D gas heatmap PNG from gas_samples.csv.")
    parser.add_argument("--input", type=Path, default=project_dir / "results" / "gas_samples.csv")
    parser.add_argument("--output", type=Path, default=project_dir / "results" / "gas_heatmap.png")
    parser.add_argument("--grid-size", type=int, default=90, help="Interpolation grid resolution per axis.")
    parser.add_argument("--vmin", type=float, default=0.0, help="Minimum ppm value for the fixed color scale.")
    parser.add_argument("--vmax", type=float, default=130.0, help="Maximum ppm value for the fixed color scale.")
    return parser.parse_args()


def parse_active_sources(row: dict[str, str]) -> list[dict[str, float | str]]:
    """Read new multi-source metadata, falling back to old single-source CSV."""
    if row.get("active_sources_json"):
        try:
            sources = json.loads(row["active_sources_json"])
        except json.JSONDecodeError:
            sources = []
        parsed_sources: list[dict[str, float | str]] = []
        for source in sources:
            parsed_sources.append({"name": str(source["name"]), "x": float(source["x"]), "y": float(source["y"])})
        return parsed_sources

    if row.get("active_zone") and row.get("active_source_x") and row.get("active_source_y"):
        return [
            {
                "name": row["active_zone"],
                "x": float(row["active_source_x"]),
                "y": float(row["active_source_y"]),
            }
        ]

    return []


def read_samples(csv_path: Path) -> list[dict[str, float | str | list[dict[str, float | str]]]]:
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    rows: list[dict[str, float | str | list[dict[str, float | str]]]] = []
    with csv_path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        missing = REQUIRED_COLUMNS.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing required CSV columns: {', '.join(sorted(missing))}")

        for row in reader:
            rows.append(
                {
                    "x": float(row["x"]),
                    "y": float(row["y"]),
                    "ppm": float(row["ppm"]),
                    "scenario": row.get("scenario", row.get("active_zone", "single_source")),
                    "active_sources": parse_active_sources(row),
                }
            )

    if not rows:
        raise ValueError(f"CSV has no samples: {csv_path}")
    return rows


def axis_values(min_value: float, max_value: float, count: int) -> list[float]:
    if count < 2:
        raise ValueError("--grid-size must be at least 2")
    step = (max_value - min_value) / (count - 1)
    return [min_value + step * i for i in range(count)]


def idw_interpolate(samples: list[dict[str, float | str | list[dict[str, float | str]]]], grid_size: int) -> tuple[list[float], list[float], list[list[float]]]:
    xs = [float(row["x"]) for row in samples]
    ys = [float(row["y"]) for row in samples]
    margin = 0.75
    grid_xs = axis_values(min(xs) - margin, max(xs) + margin, grid_size)
    grid_ys = axis_values(min(ys) - margin, max(ys) + margin, grid_size)

    grid: list[list[float]] = []
    for gy in grid_ys:
        row_values: list[float] = []
        for gx in grid_xs:
            weighted_sum = 0.0
            weight_total = 0.0
            for sample in samples:
                dx = gx - float(sample["x"])
                dy = gy - float(sample["y"])
                distance_sq = dx * dx + dy * dy
                if distance_sq < 1.0e-9:
                    weighted_sum = float(sample["ppm"])
                    weight_total = 1.0
                    break
                weight = 1.0 / math.pow(distance_sq, 1.25)
                weighted_sum += weight * float(sample["ppm"])
                weight_total += weight
            row_values.append(weighted_sum / weight_total)
        grid.append(row_values)

    return grid_xs, grid_ys, grid


def safe_filename_part(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", value.strip())
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    return cleaned or "unknown"


def scenario_heatmap_path(output_path: Path, scenario: str, active_sources: list[dict[str, float | str]]) -> Path:
    heatmap_dir = output_path.parent / "heatmaps"
    heatmap_dir.mkdir(parents=True, exist_ok=True)

    if active_sources:
        active_part = "_".join(safe_filename_part(str(source["name"])) for source in active_sources)
    else:
        active_part = "none"

    filename = f"gas_heatmap_{safe_filename_part(scenario)}_{active_part}.png"
    if len(filename) > 140:
        filename = f"gas_heatmap_{safe_filename_part(scenario)}_sources_{len(active_sources)}.png"
    return heatmap_dir / filename


def main() -> int:
    args = parse_args()
    if args.vmax <= args.vmin:
        print("--vmax must be greater than --vmin")
        return 2

    try:
        samples = read_samples(args.input)
    except (FileNotFoundError, ValueError) as exc:
        print(exc)
        print("Run ./scripts/run_mapper.sh random first to generate simulated samples.")
        return 1

    matplotlib_stderr = io.StringIO()
    try:
        with contextlib.redirect_stderr(matplotlib_stderr):
            import matplotlib.pyplot as plt
    except Exception as exc:
        print(f"Could not import matplotlib: {exc}")
        details = matplotlib_stderr.getvalue().strip()
        if details:
            first_line = details.splitlines()[0]
            print(f"Matplotlib/NumPy detail: {first_line}")
        print("CSV generation is independent from plotting. To enable heatmaps, repair plotting dependencies, for example:")
        print("  python3 -m pip install matplotlib numpy")
        return 1

    grid_xs, grid_ys, grid = idw_interpolate(samples, args.grid_size)
    sample_xs = [float(row["x"]) for row in samples]
    sample_ys = [float(row["y"]) for row in samples]
    sample_ppm = [float(row["ppm"]) for row in samples]
    scenario = str(samples[0].get("scenario", "unknown"))
    active_sources = samples[0]["active_sources"]
    if not isinstance(active_sources, list):
        active_sources = []

    args.output.parent.mkdir(parents=True, exist_ok=True)

    figure, axis = plt.subplots(figsize=(9, 6))
    image = axis.imshow(
        grid,
        extent=[min(grid_xs), max(grid_xs), min(grid_ys), max(grid_ys)],
        origin="lower",
        cmap="inferno",
        alpha=0.88,
        aspect="equal",
        vmin=args.vmin,
        vmax=args.vmax,
    )
    axis.scatter(sample_xs, sample_ys, c=sample_ppm, cmap="inferno", s=16, edgecolors="white", linewidths=0.25, vmin=args.vmin, vmax=args.vmax)
    if active_sources:
        source_xs = [float(source["x"]) for source in active_sources]
        source_ys = [float(source["y"]) for source in active_sources]
        label = "active sources" if len(active_sources) > 1 else f"active source: {active_sources[0]['name']}"
        axis.scatter(source_xs, source_ys, marker="*", s=260, c="cyan", edgecolors="black", linewidths=0.8, label=label)
    else:
        axis.scatter([], [], marker="*", s=260, c="cyan", edgecolors="black", linewidths=0.8, label="clean air / no active source")
    axis.scatter([0.0], [0.0], marker="s", s=95, c="#2f6fff", edgecolors="white", linewidths=0.8, label="START / SAFE_EXIT")
    axis.plot(sample_xs, sample_ys, color="white", linewidth=1.0, alpha=0.65, label="simulated route")
    axis.set_title(f"Simulated Gas Concentration Heatmap ({scenario}, sources={len(active_sources)})")
    axis.set_xlabel("x position [m]")
    axis.set_ylabel("y position [m]")
    axis.grid(True, color="white", alpha=0.18)
    axis.legend(loc="upper right")
    colorbar = figure.colorbar(image, ax=axis)
    colorbar.set_label("gas concentration [ppm]")
    figure.tight_layout()
    figure.savefig(args.output, dpi=170)
    archived_output = scenario_heatmap_path(args.output, scenario, active_sources)
    shutil.copyfile(args.output, archived_output)
    print(f"Saved heatmap: {args.output}")
    print(f"Saved scenario heatmap: {archived_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
